config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "home#index"
  resources :users
  resources :listings do
    resources :reviews
  end
  resource :favorites
  get 'profile', to: 'users#show'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  validates :name, :presence => true
  validates :location, :presence => true
  has_many :reviews
  has_many :favorites
  has_many :fans, through: :favorites, source: :user

  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def rating
    reviews.average(:rating).to_i
  end

  def self.search(search_string)
    location_results = self.basic_search(location: search_string)
  end

  def self.most_popular(number)
    self.all.sort_by { |listing| -listing.fans.count }[0...number]
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @search_string = params[:search_string]
    if params[:slider]
      # refine search
      @price_range = params[:slider].split(",").map { |endpoint| endpoint.to_i }
      @search_results = Listing.search(@search_string).select { |listing|
        listing.price && listing.price.between?(@price_range[0], @price_range[1]) }
      else
        @search_results = Listing.search(@search_string)
      end
    end

    def create
      listing = current_user.listings.new(listing_params)
      if listing.save
        flash[:notice] = "You've successfully created a listing!"
        redirect_to listing_path(listing)
      else
        flash[:alert] = "You're doing it wrong."
        redirect_to :back
      end
    end

    def show
      @listing = Listing.find(params[:id])
    end

    def edit
      @listing = Listing.find(params[:id])
    end

    def update
      @listing = Listing.find(params[:id])
      @listing.update(listing_params)
      redirect_to listing_path(@listing)
    end

    def destroy
      @listing = Listing.find(params[:id])
      @listing.destroy
      redirect_to listings_path
    end

    private
    def listing_params
      params.require(:listing).permit(:name, :location, :image, :description,
      :price, :guest_number, :toilet, :shower, :outlet, :pets)
    end
  end

app/views/listings/edit.html.erb
<%= form_for @listing do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form-group">
  <%= f.label :location%>
  <%= f.text_field :location%>
</div>
<div class="form-group">
  <%= f.label :description%>
  <%= f.text_field :description%>
</div>
<div class="form-group">
  <%= f.label :price%>
  <%= f.text_field :price%>
</div>
<div class="form-group">
  <%= f.label :guest_number%>
  <%= f.text_field :guest_number%>
</div>
<div class="form-group">
  <%= f.label :toilet%>
  <div class="form-group">
    <%= f.label :toilet, "Yes"%>
    <%= f.radio_button :toilet, false%>
    <%= f.label :toilet, "No"%>
    <%= f.radio_button :toilet, false, checked:false%>
  </div>
</div>
<div class="form-group">
  <%= f.label :shower%>
  <div class="form-group">
    <%= f.label :shower, "Yes"%>
    <%= f.radio_button :shower, true%>
    <%= f.label :shower, "No"%>
    <%= f.radio_button :shower, false, checked:false%>
  </div>
</div>
<div class="form-group">
  <%= f.label :outlet%>
  <div class="form-group">
    <%= f.label :outlet, "Yes"%>
    <%= f.radio_button :outlet, true%>
    <%= f.label :outlet, "No"%>
    <%= f.radio_button :outlet, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :pets%>
  <div class="form-group">
    <%= f.label :pets, "Yes"%>
    <%= f.radio_button :pets, true%>
    <%= f.label :pets, "No"%>
    <%= f.radio_button :pets, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, autocomplete: "off" %>
</div>

<%= f.submit "Submit"%>
<% end %>

app/views/listings/index.html.erb
<!-- <h4>Refine your search for a specific price range</h4>
<form action="<%= listings_path %>" method = "get">
  <%= hidden_field_tag "search_string", @search_string %>
  <input id="ex2" type="text" name="slider" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[10,1000]"/>
  <br>
  <%= submit_tag "Refine Search", class: "btn btn-primary" %>
  <script>
  var slider = new Slider('#ex2', {});
  </script>
</form> -->

<!-- <h3> <%= @search_results.length %> results for <strong><%= @search_string %></strong>
  <% if @price_range %>
  with price between $<%= @price_range.first %> and $<%= @price_range.last %>
  <% end %>
</h3> -->
<!-- # all of the above is additional functionality that was a bit buggy, so it is commented out until I can get a work-around -->

<!-- This below--lets you search by any keyword that matches one in the listing name -->
<ul>
  <% @search_results.each do |listing| %>
  <li>
    <div>
      <%= image_tag listing.image.url(:thumb) %>
    </div>
    <%= link_to listing.name, listing_path(listing) %>
  </li>
  <% end %>
</ul>

app/views/listings/new.html.erb
<%= form_for Listing.new do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form-group">
  <%= f.label :location%>
  <%= f.text_field :location%>
</div>
<div class="form-group">
  <%= f.label :description%>
  <%= f.text_field :description%>
</div>
<div class="form-group">
  <%= f.label :price%>
  <%= f.text_field :price%>
</div>
<div class="form-group">
  <%= f.label :guest_number%>
  <%= f.text_field :guest_number%>
</div>
<!-- These checkboxes need work are only semifunctional at this time -->
<div class="form-group">
  <%= f.label :toilet%>
  <div class="form-group">
    <%= f.label :toilet, "Yes"%>
    <%= f.radio_button :toilet, true%>
    <%= f.label :toilet, "No"%>
    <%= f.radio_button :toilet, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :shower%>
  <div class="form-group">
    <%= f.label :shower, "Yes"%>
    <%= f.radio_button :shower, true%>
    <%= f.label :shower, "No"%>
    <%= f.radio_button :shower, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :outlet%>
  <div class="form-group">
    <%= f.label :outlet, "Yes"%>
    <%= f.radio_button :outlet, true%>
    <%= f.label :outlet, "No"%>
    <%= f.radio_button :outlet, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :pets%>
  <div class="form-group">
    <%= f.label :pets, "Yes"%>
    <%= f.radio_button :pets, true%>
    <%= f.label :pets, "No"%>
    <%= f.radio_button :pets, false, checked:true%>
  </div>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, autocomplete: "off" %>
</div>
<%= f.submit "Submit"%>
<% end %>

app/views/listings/show.html.erb
<h1> PDX Properteez</h1>
<div class="listing_title_info">
  <%= image_tag @listing.image.url(:original), :class => "full_width_image" %>
</div>

<div class="listing_info row">
  <div class="col-md-2 col-md-offset-1">
    <p>
      <%= image_tag @listing.user.avatar.url(:medium), :class => "img-circle", :width => "100px" %>
    </p>
    <h5><%= @listing.user.name %></h5>
  </div>
  <div class="col-md-4">
    <h3><%= @listing.name %> | <%= @listing.location %></h3>
    <h5><%= render "layouts/rating", rateable: @listing %> (<%= @listing.reviews.count %>)</h5>
    <h5><%= @listing.fans.count %> favorites</h5>
  </div>
  <div class="col-md-2">
    <% if user_signed_in? %>
    <% if @listing.user == current_user || current_user.admin? %>
    <%= link_to "Edit Listing", edit_listing_path(@listing), class: "btn btn-warning"%>
    <%= link_to "Delete Listing", listing_path(@listing), method: :delete, class: "btn btn-danger"%>
    <% elsif !current_user.favorited?(@listing) %>
    <%= link_to "Add as Favorite", favorites_path(favorite: {user_id: current_user.id,
      listing_id: @listing.id}),
      method: :post,
      class: "btn btn-success" %>
      <% end %>
      <% end %>
    </div>
  </div>

  <div class="row listing_description">
    <div class="col-md-4 col-md-offset-1">
      <h4>About This Listing</h4>
      <p><%= @listing.description%></p>
      <hr>
      Prices <span class="pull-right"><strong><%= @listing.price %></strong></span>
      <hr>
      Guests <span class="pull-right"><strong><%= @listing.guest_number%><br></strong></span>
      <hr>
      Toilets <span class="pull-right"><%= has_amenity(@listing.toilet) %></span>
      <hr>
      Shower <span class="pull-right"><%= has_amenity(@listing.shower) %></span>
      <hr>
      Outlet <span class="pull-right"><%= has_amenity(@listing.outlet) %></span>
      <hr>
      Pets <span class="pull-right"><%= has_amenity(@listing.pets) %></span>
    </div>
  </div>

  <hr>
  <div class="listing_reviews">
    <div class="col-md-4 col-md-offset-1">
      <h4><%= @listing.reviews.count %> Reviews | <%= render "layouts/rating", rateable: @listing %>
        <%= link_to "Add Review", new_listing_review_path(@listing), class: "btn btn-success pull-right" %>
      </h4>
      <hr>
      <ul class="list-unstyled">
        <% @listing.reviews.each do |review| %>
        <li>
          <%= image_tag review.user.avatar.url(:thumb), :class => "img-circle", :width => "60px" %>
          <%= review.user.name %>
          <div>
            <%= review.text %>
            <%= render "layouts/rating", rateable: review %>
            <% if user_signed_in? %>
            <% if review.user == current_user || current_user.admin? %>
            <%= link_to "Edit Review", edit_listing_review_path(@listing, review) %>
            <%= link_to "Delete Review", listing_review_path(@listing, review), method: :delete %>
            <% end %>
            <% end %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>