config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "home#index"
  resources :users
  resources :listings do
    resources :reviews
  end
  resource :favorites
  get 'profile', to: 'users#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #'popular yards' = "air conditiong homes" also "best air conditioning homes takes the place of 'most-popular'"
    @popular_yards = Listing.most_popular(4)
  end
end

app/views/home/index.html.erb
<!-- This is the body of the home page and styling for the photos to all be listed as circles on the page -->
<div class="container">
  <div class='heading'>
    <strong> PDX Properteez</strong> 
  </div>
  <h3> Air Conditioning. Toilets.</h3>
   <br><h4>(its Portland, you think you can have <em>both</em>?)<h4>

  <div class='row popular-images'>
    <% @popular_yards[0..1].each do |listing| %>
    <div class='col-md-4 col-md-offset-1'>
      <%= link_to listing_path(listing) do %>
      <%= image_tag listing.image.url(:medium), class: "img-circle popular-image" %>
      <% end %>
    </div>
    <% end %>
  </div>

  <% if @popular_yards.length > 1 %>
  <div class='row popular-images'>
    <% @popular_yards[2..3].each do |listing| %>
      <div class='col-md-4 col-md-offset-1'>
      <%= link_to listing_path(listing) do %>
        <%= image_tag listing.image.url(:medium), class: 'img-circle popular-image' %>
        <% end %>
      </div>
      <% end %>

    </div>
    <% end %>
  </div>