config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "home#index"
  resources :users
  resources :listings do
    resources :reviews
  end
  resource :favorites
  get 'profile', to: 'users#show'
end

app/views/layouts/_rating.html.erb
<% if rateable.rating %>
  <% rateable.rating.times do %>
    <span class='glyphicon gliphicon-star rating'></span>
  <% end %>
  <% else %>
  No rating
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDX Properteez</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<h1> PDX Properteez </h1>
<body class="container-fluid">


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <nav class="navbar navbar-inverse navbar-fixed-top" role='navigation'>
    <ul class='nav navbar-nav'>
      <li>
        <%= link_to root_path do %>
        <%= image_tag 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ89G3i8RUZDrXv44KU0P-_iYuAksuCwK5nl9bIPpHh2190vujA', width: 75, height: 75, alt: 'Airbnb Logo'%>
        <% end %>
      </li>
    </ul>

    <form action="<%= listings_path %>" method = "get" class="search pull-left form-inline">
      <%= text_field_tag(:search_string, nil, placeholder: "Where do you want to go?", class:"form-control") %>
    </form>


    <span class="pull-right">
      <% if user_signed_in? %>
      <%= image_tag current_user.avatar.url(:thumb), :class => "img-circle nav_host_picture", :width => "75" %>
      <% end %>
      <ul class='nav navbar-nav'>
        <% if user_signed_in? %>
            <li><%= link_to 'Profile', profile_path %></li>
            <li> <%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
      <%= link_to "List Your Space", new_listing_path, :class => "nav_list_your_space btn-sm btnGreen" %>
    </span>



  </nav>


  <%= yield %>

</body>
</html>